### ISSUE TITLE
Whenever I use the user leaderboard

### ISSUE THREAD

**Issue by wds33817** [wds33817/test1stRound#8]
I happened to use PUT for update user /v1/user

The payload:
{
    "username": "Test111111",
    "score": "NaN"
}

It will make service crash for the website

**Comment by wds33817** [comment]
I use postman to test API by the way.

**Comment by asanchezgiraldo** [comment]
without response" method=PUT path="/v1/user" host=supervillain.herokuapp.com request_id=04751563-dfd6-4579-a874-bb2997a92b14 fwd="211.29.234.243" dyno=web.1 connect=0ms service=1423ms status=503 bytes=0 protocol=https
2021-11-23T19:31:10.560685+00:00 app[web.1]: /app/app/controller/sql.js:58
2021-11-23T19:31:10.560696+00:00 app[web.1]:           if (result.rowCount == 0) {
2021-11-23T19:31:10.560696+00:00 app[web.1]:                      ^
2021-11-23T19:31:10.560696+00:00 app[web.1]: 
2021-11-23T19:31:10.560699+00:00 app[web.1]: TypeError: Cannot read property 'rowCount' of undefined
2021-11-23T19:31:10.560700+00:00 app[web.1]:     at /app/app/controller/sql.js:58:22
2021-11-23T19:31:10.560701+00:00 app[web.1]:     at Query.callback (/app/node_modules/pg-pool/index.js:369:18)
2021-11-23T19:31:10.560701+00:00 app[web.1]:     at Query.handleError (/app/node_modules/pg/lib/query.js:146:19)
2021-11-23T19:31:10.560702+00:00 app[web.1]:     at Connection.connectedErrorMessageHandler (/app/node_modules/pg/lib/client.js:236:17)
2021-11-23T19:31:10.560702+00:00 app[web.1]:     at Connection.emit (node:events:369:20)
2021-11-23T19:31:10.560703+00:00 app[web.1]:     at TLSSocket.<anonymous> (/app/node_modules/pg/lib/connection.js:121:12)
2021-11-23T19:31:10.560703+00:00 app[web.1]:     at TLSSocket.emit (node:events:369:20)
2021-11-23T19:31:10.560703+00:00 app[web.1]:     at addChunk (node:internal/streams/readable:313:12)
2021-11-23T19:31:10.560704+00:00 app[web.1]:     at readableAddChunk (node:internal/streams/readable:288:9)
2021-11-23T19:31:10.560704+00:00 app[web.1]:     at TLSSocket.Readable.push (node:internal/streams/readable:227:10)
2021-11-23T19:31:10.700188+00:00 heroku[web.1]: Process exited with status 1
2021-11-23T19:31:10.895658+00:00 heroku[web.1]: State changed from up to crashed
2021-11-23T19:31:09.150327+00:00 app[web.1]: Application used ::: alejandro200
